//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: ixpeobssim
// Function header: ixpeobssimFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createixpeobssimFunctionMap();

extern "C"  {


	XSCCall      polconst;
	XSCCall      pollin;
	XSCCall      polpow;
	XSCCall      polconst;
	XSCCall      pollin;
	XSCCall      polpow;
}


#endif
