//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: ixpeobssim
// Function body: ixpeobssimFunctionMap.cxx

#include    "ixpeobssimFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>

void 
createixpeobssimFunctionMap()
{


	XSFunctionMap["polconst"] = new XSCall<XSCCall>(polconst);
	XSFunctionMap["pollin"]   = new XSCall<XSCCall>(pollin);
	XSFunctionMap["polpow"]   = new XSCall<XSCCall>(polpow);
	XSFunctionMap["apolconst"] = new XSCall<XSCCall>(polconst);
	XSFunctionMap["apollin"]  = new XSCall<XSCCall>(pollin);
	XSFunctionMap["apolpow"]  = new XSCall<XSCCall>(polpow);

}
