//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: ixpeobssim Created :
// Initializer: ixpeobssim.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "ixpeobssimFunctionMap.h"
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Ixpeobssim_Init(Tcl_Interp* tclInterp);
extern "C" int Ixpeobssim_SafeInit(Tcl_Interp* tclInterp);

int Ixpeobssim_Init(Tcl_Interp* tclInterp)
{
        return Ixpeobssim_SafeInit(tclInterp);
}

int Ixpeobssim_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "ixpeobssim";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createixpeobssimFunctionMap();
        XSModelFunction::updateComponentList
              ("/data/work/ixpe/ixpeobssim/ixpeobssim/xspec/ixpeobssim_model.dat");
        return TCL_OK;

}

