name: Deploy
on:
    push:
      branches:
        - main    
      paths-ignore:
        - "README.md"
        - "**/docs/**"
        #- ".github/workflows/docs.yml"
      tags:
        - '*'

    pull_request:
      branches:
        - main

jobs:

    publish-pypi:
        name: Publish to PyPi
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools
            - name: Build package
              run: |
                  python setup.py sdist
            - name: Publish
              uses: pypa/gh-action-pypi-publish@v1.1.0
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
                  skip-existing: true

    test-publish-pypi:
        name: Build & verify PyPi
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools
            - name: Install twine
              run: |
                  python -m pip install twine
            - name: Build package
              run: |
                python setup.py sdist

            - name: List result
              run: |
                  ls -lh dist
            - name: Check long_description
              run: |
                  python -m twine check dist/*
