name: CI
on:
    push:
      branches:
        - main    
      paths-ignore:
        - "README.md"
        - "**/docs/**"
      tags:
        - '*'

    pull_request:
      branches:
        - main
        
    schedule:
        - cron: "0 11 * * 1"

jobs:

    test-pip:
        name: Test using pip install
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest", "macos-latest"]
                python-version: [3.9]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel
                  pip install pytest
                  pip install -e .
            - name: Test pip on ${{ matrix.python-version }}
              run: |
                  cd tests
                  python -m pytest -vv .

